# Generated by Django 5.2.5 on 2025-08-21 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=50, unique=True
            ),
        ),
    ]
