# Generated by Django 5.2.5 on 2025-08-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_match_match_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="match_id",
        ),
        migrations.CreateModel(
            name="CasinoBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=50)),
                ("bet_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "winnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casino_bets",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
