# Generated by Django 5.2.5 on 2025-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_match_match_id_casinobet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("withdraw_reversal", "Withdrawal Reversal"),
                    ("bet_placed", "Bet Placed"),
                    ("bet_won", "Bet Won"),
                ],
                max_length=20,
            ),
        ),
    ]
