# Generated by Django 5.2.4 on 2025-08-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bet",
            name="match",
        ),
        migrations.RemoveField(
            model_name="bet",
            name="user_profile",
        ),
        migrations.DeleteModel(
            name="Match",
        ),
        migrations.DeleteModel(
            name="Bet",
        ),
    ]
