# Generated by Django 5.2.4 on 2025-08-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_bet_match_remove_bet_user_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matchess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField(unique=True)),
                ("match_name", models.CharField(max_length=100)),
                ("Team1", models.CharField(max_length=50)),
                ("Team2", models.CharField(max_length=50)),
                (
                    "winner_team",
                    models.CharField(
                        blank=True,
                        choices=[("Team1", "Team1"), ("Team2", "Team2")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("UpComing", "UpComing"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                        ],
                        default="UpComing",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/")),
                ("url", models.URLField()),
            ],
        ),
    ]
